[package]
name = "async-lock"
version = "2.0.1"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "Async locking primitives"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/stjepang/async-lock"
homepage = "https://github.com/stjepang/async-lock"
documentation = "https://docs.rs/async-lock"
keywords = ["asynchronous", "mutex", "lock", "synchronization"]
categories = ["asynchronous", "concurrency"]
readme = "README.md"

[dependencies]
async-barrier = "1.0.0"
async-mutex = "1.2.0"
async-rwlock = "1.1.0"
async-semaphore = "1.0.0"
