[package]
name = "async-lock"
# When publishing a new version:
# - Update CHANGELOG.md
# - Create "v2.x.y" git tag
version = "2.7.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
rust-version = "1.48"
description = "Async synchronization primitives"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/smol-rs/async-lock"
keywords = ["lock", "mutex", "rwlock", "semaphore", "barrier"]
categories = ["asynchronous", "concurrency"]
exclude = ["/.*"]

[dependencies]
event-listener = "2"
event-listener-strategy = { git = "https://github.com/smol-rs/event-listener.git" }

[dev-dependencies]
async-channel = "1.5.0"
fastrand = "1.4.0"
futures-lite = "1.12.0"

[target.'cfg(any(target_arch = "wasm32", target_arch = "wasm64"))'.dev-dependencies]
wasm-bindgen-test = "0.3"

[patch.crates-io]
event-listener = { git = "https://github.com/smol-rs/event-listener.git" }
