[package]
name = "async-lock"
version = "1.0.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "Reference-counted async lock"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/stjepang/async-lock"
homepage = "https://github.com/stjepang/async-lock"
documentation = "https://docs.rs/async-lock"
keywords = ["async", "file", "stdio", "stdin", "process"]
categories = ["asynchronous", "concurrency"]
readme = "README.md"

[dependencies]
event-listener = "1.0.0"

[dev-dependencies]
smol = "0.1.6"
