[package]
name = "async-lock"
version = "2.2.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "Async synchronization primitives"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/stjepang/async-lock"
homepage = "https://github.com/stjepang/async-lock"
documentation = "https://docs.rs/async-lock"
keywords = ["lock", "mutex", "rwlock", "semaphore", "barrier"]
categories = ["asynchronous", "concurrency"]
readme = "README.md"

[dependencies]
event-listener = "2.5.1"

[dev-dependencies]
async-channel = "1.5.0"
fastrand = "1.4.0"
futures-lite = "1.10.1"
