[package]
name = "async-lock"
version = "1.1.4"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "Reference-counted async lock"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/stjepang/async-lock"
homepage = "https://github.com/stjepang/async-lock"
documentation = "https://docs.rs/async-lock"
keywords = ["asynchronous", "mutex", "lock", "synchronization"]
categories = ["asynchronous", "concurrency"]
readme = "README.md"

[dependencies]
async-mutex = "1.1.5"

[dev-dependencies]
smol = "0.1.18"
futures = "0.3.5"
